name: smartnav
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
    
  shared_preferences: ^2.5.3
  pinput: ^5.0.0
  provider: ^6.1.2
  speech_to_text: ^7.0.0
  sliding_up_panel: ^2.0.0+1
  intl: ^0.19.0
  cupertino_icons: ^1.0.8 
  flutter_animate: ^4.5.2
  google_maps_flutter: ^2.6.1
  google_fonts: ^6.2.1
  camera: ^0.11.0
  camera_web: ^0.3.3
  image_picker: ^1.1.2

  flutter_local_notifications: ^17.1.2
  geolocator: ^11.0.0
  geocoding: ^4.0.0
  permission_handler: ^11.3.1
  http: ^1.2.1

  flutter_map: ^6.1.0
  latlong2: ^0.9.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/welcome_bg.png


